version: '3'

services:
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=splitwise
    volumes:
      - ./internal/db/migration:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  server:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=splitwise
        - DATABASE_HOST=postgres
      depends_on:
        - postgres

      ports:
        - "8080:8080"
